name: Keep n8n Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:          # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl n8n URL
        run: curl -s https://n8n-09rm.onrender.com/workflow/bwoOVFLV2xjCx8pk > /dev/null
