name: Keep n8n Workflow Alive (5)

on:
  schedule:
    - cron: "*/5 * * * *"   # run every 5 minutes (UTC)
  workflow_dispatch:         # allows manual run from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl n8n workflow URL (with retries)
        run: |
          curl --retry 3 --retry-delay 10 -s https://n8n-09rm.onrender.com/workflow/bwoOVFLV2xjCx8pk > /dev/null


# 2️⃣ Send Telegram notification
curl -s -X POST "https://api.telegram.org/bot8215604218:AAElUyJ0s_SKZX9Td3PTpuU7Od0m-KMW2Nw/sendMessage" \
     -d chat_id=6430910531 \
     -d text="✅ n8n workflow was triggered successfully at $(date '+%Y-%m-%d %H:%M:%S')"
