name: Keep n8n Webhook Alive (5)

on:
  schedule:
    - cron: "*/5 * * * *"   # run every 5 minutes (UTC)
  workflow_dispatch:         # allows manual run from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl n8n webhook URL (with retries)
        run: |
          curl --retry 3 --retry-delay 3 -s https://n8n-09rm.onrender.com/webhook/c0b7a517-5719-42da-af87-81cd638a3d42 > /dev/null

